### PR TITLE
Remove timestamp caching and re-enable CI

### LINKED ISSUE #7: Reenable the CI
The cache config in `.github-disabled` does not work. Figure out why, fix it, and re-enable the CI.

### PR DESCRIPTION
**Pull request by hinerm**
Closes #7

### CODE REVIEW

File: archives-updated.sh [hunk 1]
```diff
@@ -0,0 +1,58 @@
+#!/bin/bash
+
+# Emits 'true' if a Fiji app bundle has been created since the most recent
```
Comment (ctrueden) [inline archives-updated.sh]: I find the name `archives-updated.sh` confusing. What do you think about renaming this to something like `fiji-archive-status.sh` and making the return strings more explicit like `up-to-date` vs `update-needed`?

File: build.sh [hunk 2]
```diff
@@ -1,72 +1,35 @@
 #!/bin/bash
 set -e
 
-CACHE_DIR=cache
+if [ "$CI" = "true" ]
+then
+	# Running on CI. Use a cache folder off the home directory.
+	CACHE_DIR="$HOME/cache"
```
Comment (ctrueden) [inline build.sh]: Since the caching step was removed from the GHA workflow, we don't need this case logic anymore, do we? You could just use `Fiji.app` without the word "cache" involved at all. (If it's not actually going to be cached, I would avoid using the term "cache")

**Review by ctrueden — CHANGES_REQUESTED** [review]
Thank you for fixing this! :rocket:

**Comment by hinerm** [comment]
Thanks @ctrueden! Are you happy with the way it looks now?

File: build.sh [hunk 3]
```diff
@@ -1,72 +1,35 @@
...
-    ;;
-  *)
-    date1=`date --date="$date1" +%s`
-    date2=`date --date="$date2" +%s`
-    date3=`date --date="$date3" +%s`
-    ;;
-esac
-dates=( "$date1" "$date2" "$date3" )
+# the archives-updated script will return 'false' if an update is needed
+up_to_date="$(./archives-updated.sh)"
```
Comment (ctrueden) [inline build.sh]: This needs to call `fiji-archive-status.sh`, doesn't it?

**Review by ctrueden — APPROVED** [review]

**Comment by ctrueden** [comment]
@hinerm I removed the `BASE_DIR` logic, fixed a problem with the archive status check, and made some minor tweaks. Please merge if you are satisfied with the current state!
